/**
 * NeuralSim test synthesis head (Delta cluster 2: inline tests).
 * Scans top-level functions and produces framework-appropriate skeletons.
 */

import { detectLanguage, tokenize } from './tokenizer.ts';
import type { Language } from './tokenizer.ts';
import type { TestCase, TestGenRequest, TestGenResult } from './types.ts';

export function generateTestsFor(req: TestGenRequest): TestGenResult {
  const start = Date.now();
  const { filePath, lang, source } = req;
  const lines = source.split(/\r?\n/);
  const tests: TestCase[] = [];

  const defRe = lang === 'python'
    ? /^(\s*)def\s+(test_?[A-Za-z_]\w*)\s*\(([^)]*)\)\s*:/
    : lang === 'rust'
      ? /^(\s*)fn\s+([A-Za-z_]\w*)\s*(?:<[^>]*>)?\(([^)]*)\)\s*(?:->\s*[^{]+)?\{/
      : /^(\s*)(?:export\s+)?(?:async\s+)?function\s+([A-Za-z_]\w*)\s*\(([^)]*)\)/;

  for (let i = 0; i < lines.length; i++) {
    const m = defRe.exec(lines[i]!);
    if (!m) continue;
    const name = m[2]!;
    const params = m[3]!;
    if (name.startsWith('test')) continue; // already a test

    const argNames = params.split(',').map((p) => p.split(':')[0]!.trim()).filter((p) => p.length > 0 && p !== 'self');
    const sampled = argNames.slice(0, 2);

    if (lang === 'python') {
      tests.push({
        name: `test_${name}`,
        framework: 'pytest',
        target: name,
        code: `def test_${name}():\n    """Generated by Hydra Delta-2 (NeuralSim)."""\n    result = ${name}(**{${sampled.map((s) => `"${s}": ${sampleValue(s)}`).join(', ')}})\n    assert result is not None\n`,
      });
    } else if (lang === 'rust') {
      tests.push({
        name: `test_${name}_works`,
        framework: 'cargo test',
        target: name,
        code: `#[test]\nfn test_${name}_works() {\n    // Generated by Hydra Delta-2 (NeuralSim)\n    let result = ${name}(${argNames.map((s) => sampleValue(s)).join(', ')});\n    assert!(result != ${ArgDefault});\n}\n`.replace('ArgDefault', '0'),
      });
    } else {
      tests.push({
        name: `${name} works`,
        framework: lang === 'typescript' ? 'vitest' : 'jest',
        target: name,
        code: `import { describe, it, expect } from 'vitest';\nimport { ${name} } from '${moduleName(filePath)}';\n\ndescribe('${name}', () => {\n  it('executes without throwing', () => {\n    const result = ${name}(${argNames.map((s) => sampleValue(s)).join(', ')});\n    expect(result).not.toBeUndefined();\n  });\n});\n`,
      });
    }
    if (tests.length >= 4) break;
  }

  return { tests, latencyMs: Date.now() - start };
}

const ArgDefault = '0';

function sampleValue(name: string): string {
  if (name.startsWith('is') || name.startsWith('has') || name.startsWith('should')) return 'True';
  if (name.includes('id') || name.includes('count') || name.includes('num')) return '1';
  if (name.includes('name') || name.includes('key') || name.includes('str')) return '"sample"';
  return '0';
}

function moduleName(filePath: string): string {
  const basename = filePath.split(/[\\/]/).pop() ?? 'module';
  return basename.replace(/\.(ts|js)$/, '');
}

export { detectLanguage };